name: Github Actions Demo
on:
  push:
    branches: main
    branches-ignore: .github
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: stuff
        run: echo "::set-output name=my_time::$(date)"
        id: set-time
        
      - name: output time
        run: echo "It was ${{ steps.set-time.output.my_time }}"
