name: CI Build for Docker Peter's Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-action
        with:
          who-to-greet: '@BadKarmaPete'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"