name: Pete's 1st Workflow
on: 
  workflow_dispatch:
    inputs:
      Name:
        description: input the name
        required: true
        default: peter-vdc
  schedule:
    - cron: '*/15 6 6 * *'
    
jobs:
  echo-step:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::hello ${{inputs.Name}}"
        
